name: heartbeat

heartbeat.monitors:
  - type: http
    schedule: "@every 5s"
    urls:
      - http://elasticsearch:9200
    username: ${ELASTIC_USERNAME}
    password: ${HEARTBEAT_INTERNAL_PASSWORD}

  - type: icmp
    schedule: "@every 5s"
    hosts:
      - elasticsearch

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: ${ELASTIC_USERNAME}
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [http://elasticsearch:9200]
  username: ${ELASTIC_USERNAME}
  password: ${HEARTBEAT_INTERNAL_PASSWORD}

http:
  enabled: true
  host: 0.0.0.0
