version: "3.7"

services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${ELASTIC_VERSION}
    command:
      - -e
      - --strict.perms=false
    volumes:
      - ./extensions/heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro,Z
    environment:
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD}
    networks:
      - tester
    depends_on:
      - elasticsearch
